export const GET_ALL_INTERVALS = 'GET_ALL_INTERVALS',
    CLEAR_INTERVALS = 'CLEAR_INTERVALS',
    GET_ALL_VISITS = 'GET_ALL_VISITS',
    


    SELECT_EVENT = 'SELECT_EVENT',
    DELETE_EVENT = 'DELETE_EVENT',
    OPEN_CANCEL_MODAL = 'OPEN_CANCEL_MODAL',
    CLOSE_CANCEL_MODAL = 'CLOSE_CANCEL_MODAL';

export const GET_ALL_REVIEWS = 'GET_ALL_REVIEWS', 
    GET_ALL_REVIEWS_ERROR = 'GET_ALL_REVIEWS_ERROR',
    PUT_COMMENT_ANSWER = 'PUT_COMMENT_ANSWER',
    PUT_COMMENT_ANSWER_ERROR = 'PUT_COMMENT_ANSWER_ERROR';

export const AUTH_FAIL = 'AUTH_FAIL', 
    AUTH_SUCCESS = 'AUTH_SUCCESS', 
    AUTH_START = 'AUTH_START';

export const GET_DOCTORS_PATIENTS = 'GET_DOCTORS_PATIENTS',
    GET_NOT_DOCTORS_PATIENTS = 'GET_NOT_DOCTORS_PATIENTS',
    GET_SELECTED_PATIENT_INFO = 'GET_SELECTED_PATIENT_INFO',
    SELECT_PATIENT = 'SELECT_PATIENT',
    UNSELECT_PATIENT = 'UNSELECT_PATIENT',
    GET_DATE_INTERVAL = 'GET_DATE_INTERVAL';

export const GET_ALL_TREATMENTS = 'GET_ALL_TREATMENTS',
    GET_ACTUAL_TREATMENTS = 'GET_ACTUAL_TREATMENTS',
    SELECT_VISIT = "SELECT_VISIT",
    SELECT_TREATMENT = 'SELECT_TREATMENT',
    CLEAR_VISIT_AND_TREAT = 'CLEAR_VISIT_AND_TREAT';

export const GET_DOCTOR_TODAY_INFO = 'GET_DOCTOR_TODAY_INFO',
    GET_DOCTOR_SHORT_INFO = 'GET_DOCTOR_SHORT_INFO',
    SET_EX_INTERVAL_INFO = 'SET_EX_INTERVAL_INFO',
    SWITCH_EX_INTERVAL = 'SWITCH_EX_INTERVAL';

export const INFO_DOCTOR = 'INFO_DOCTOR',
    SEND_NEW_INFO_DOCTOR = 'SEND_NEW_INFO_DOCTOR';
