export const diseasesArr = [
    {
        date: "15.09.2017",
        diseases: 'Хроническое заболевание длинное название длинное название.',
    },{
        date: "15.09.2017",
        diseases: 'Хроническое заболевание длинное название длинное название.',
    },{
        date: "15.09.2017",
        diseases: 'Хроническое заболевание длинное название длинное название.',
    },{
        date: "15.09.2017",
        diseases: 'Хроническое заболевание длинное название длинное название.',
    },{
        date: "15.09.2017",
        diseases: 'Хроническое заболевание длинное название длинное название.',
    },{
        date: "15.09.2017",
        diseases: 'Хроническое заболевание длинное название длинное название.',
    },
];

export const historyArr = [
    {
        status: "new",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    }, {
        status: "new",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    }, {
        status: "new",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    }, {
        status: "new",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },{
        status: "new",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },{
        status: "topical",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },{
        status: "extra",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },{
        status: "completed",
        date: "15.09.2017",
        time: '15:00-16:00',
        type: 'chat1',
        diagnostic: "Сахарный диабет",
        comments: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        price: "112 руб.",
        conclusion: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",
        conclusionDownload: "Заключение 252525.pdf",
        review: "Lorem ipsum dolor sit amet, consectetuer...",
    },
];